### ISSUE TITLE
Defining 1.0

### ISSUE THREAD

**Issue by wnadeau** [hired/reactor#70]
This has been in production for so long... and by semantic versioning standards it should have been 1.0 a long time ago.

So I'm taking time to define what 1.0 means to me, and it's essentially this:

### Reducing Bloat To A Discrete Surface Area

Rather than try to make Reactor an opinionated set of conventions (that historically have been just plain wrong), I'd like to remove _anything_ that isn't just "easy pub sub workers". If an application wants to add conventions on top of Reactor, it's all quite possible to do at the application layer. If someone wants to share open source conventions on top of this, make a gem!

> A reactor ecosystem of opt-in libraries is going to be far stronger than a bloated mess.

So with that philosophy/direction, I'd like to do the following

- Reactor 1.0 Roadmap
    - [x] let subscribers pass through sidekiq options to choose their queue, retry, etc (see #68)
    - [x] kill database subscriber feature (see #69)
    - [x] rebase (and later merge) #30 - production console publish confirmations
    - [x] fix `fired_at` value's semantics (see #35)
    - [x] kill in_memory feature (see #71)
    - [x] kill controller/concerns, if someone wants to extract it to a gem go for it. (see #72)
    - [x] apps should decide where to include `Reactor::Subscribable` & `Publishable`(see #64)
- Stretch Goals
    - [x] kill test_mode and let applications use basic `expect()`/`allow()` syntax

### Upgrade Guide For Users

* `drop_table :subscribers`, or keep it and write your own static `*` subscriber that uses it.
* on that note, pull any of the above removed features downstream into your app as needed, make a `reactor_*` gem and.
* update `ActivityLogger`-like classes to use `published_at` instead of `fired_at`, which is now written at the appropriate time.
* handle on_event sidekiq wrapper job migration detailed in #73 
* include `Reactor::Publishable` and `Reactor::Subscribable` on `ActiveRecord::Base` or `ApplicationRecord`, or wherever you want it now if you don't want it there any more. (see #64)

**Comment by wnadeau** [comment]
aaand we're done. ✔️
